### ISSUE TITLE
"Error: contains a blank line"

### ISSUE THREAD

**Issue by pingfreud** [MarcoDVisser/choosecolor#2]
Apparently, it has to do with devtools adding blanklines to the DESCRIPTION file. 

It was supposed to be fixed according to [this](https://github.com/hadley/devtools/issues/394) thread, however I still get the same error while trying to install it.

**Comment by MarcoDVisser** [comment]
Hi pingfreud! Thanks for reporting this, the packages hasn't been updated for a while. I'll take a look at this issue as soon as soon I get a chance. Should be solvable.

**Comment by MarcoDVisser** [comment]
The blank line issue was fixed. Sorry for the delay!
